### PR TITLE
Update Config-DisableWindowsStoreUpdates.wsf

### PR DESCRIPTION
**Pull request by coldscientist**
Allow Enabling Windows Store Updates into an On-line OS.

### CODE REVIEW

**Comment by LipkeGu** [comment]
Are you sure it is the correct file?! You have changed the "Disabke" but your changes are more suiteable in the "Enable" file.

https://github.com/DeploymentResearch/DRFiles/blob/9152996d551515190436bb7d7c0006c3845d6047/Scripts/Config-DisableWindowsStoreUpdates.wsf#L1

**Comment by LipkeGu** [comment]
https://github.com/DeploymentResearch/DRFiles/blob/master/Scripts/Config-DisableWindowsStoreUpdates.wsf#L15

Line 15: Seems to be a typo.

**Comment by arwidmark** [comment]
Thanks, fixed the typo.

**Comment by LipkeGu** [comment]
In this Script and as i see you fixed it here but not in your other scripts… like Disable Cortana... im Always see a line like:

```
UpdateDevicePath = Success
```

Did we Need this or is it a bug?

https://github.com/DeploymentResearch/DRFiles/blob/9152996d551515190436bb7d7c0006c3845d6047/Scripts/Config-DisableWindowsStoreUpdates.wsf#L34

**Comment by sanchezjei** [comment]
Is this change correct?
Should it be deleting the registry keys rather than changing their values? The language on lines 42 and 57 indicate that it's meant to "Enable" instead of "Disable"...

**Comment by coldscientist** [comment]
If you use Config-DisableWindowsStoreUpdates.wsf to disable Windows Store updates after installing Windows 10 (e.g. to avoid it installing windows store apps after installing through MDT - a process that can take a while, delaying the deploy process), it will set the keys that my script deleted. So my script only has the feature to re-enable windows store updates deleting the keys that was set by Config-DisableWindowsStoreUpdates.wsf. Deleting the keys restore the default behavior from Windows 10, that is download windows store updates.

**Pull request merged**
